apiVersion: v1
kind: Service
metadata:
  name: frigo-frontend
  namespace: frigo
spec:
  type: NodePort
  selector:
    app: frigo-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
